### ISSUE TITLE
Pause timer

### ISSUE THREAD

**Issue by Syzygianinfern0** [ivoronin/TomatoBar#50]
I can only stop the timer. A way to pause the timer would be really cool.

**Comment by ivoronin** [comment]
This would defeat the purpose of the app.

https://en.wikipedia.org/wiki/Pomodoro_Technique:
> A goal of the technique is to reduce the effect of internal and external interruptions on [focus](https://en.wikipedia.org/wiki/Focus_(cognitive_process)) and [flow](https://en.wikipedia.org/wiki/Flow_(psychology)). A pomodoro is indivisible; when interrupted during a Pomodoro, either the other activity must be recorded and postponed (using the inform – negotiate – schedule – call back strategy[[6]](https://en.wikipedia.org/wiki/Pomodoro_Technique#cite_note-6)) or the pomodoro must be abandoned.[[1]](https://en.wikipedia.org/wiki/Pomodoro_Technique#cite_note-Cirillo-1)[[5]](https://en.wikipedia.org/wiki/Pomodoro_Technique#cite_note-Noteberg-5)[[7]](https://en.wikipedia.org/wiki/Pomodoro_Technique#cite_note-7)

**Comment by Karta775** [comment]
**In the off-chance that this is up for debate:** 

Would you consider this functionality being opt-in via settings? I can imagine numerous distractions that could happen during a pomodoro session that aren't the sort of thing you can just record and postpone, and also aren't worth abandoning the pomodoro for. For example, if someone you live with starts a conversation with you. It would be nice to have the ability to pause the pomodoro since it's rude to postpone a conversation and it's annoying to discard your pomodoro for a conversation.

For me, this app is exactly what I was hoping for in a pomodoro, it's simple and stays out of my way unlike others I've used, but the lack of a pause adds friction to my workflow.

If the answer is no, then fair enough. It's your project 👍

**Comment by iamtodor** [comment]
@ivoronin Is there any chance you would be open to discussing this feature? +1 person who wants this feature, which is off by default but can be turned on in the settings. 

Judging by the number of 👍's under the first message, I think people would like to have this option :)

Could you please reopen this issue so people can have their say and you can get the feedback to help you decide?

**Comment by iamtodor** [comment]
We all have different reasons for pausing the current session rather than turning it off. By adding this feature, I see more freedom for someone who lacks this functionality, while not restricting the ability of people who do not want to use Pomodoro Time in this way

**Comment by ElliotRoe** [comment]
Would also love this

**Comment by DesignSkeptic** [comment]
+ 1 Other closed source apps have this.
